DROP TABLE baza CASCADE;
DROP TABLE filmy CASCADE;
DROP TABLE glowni_aktorzy CASCADE;
DROP TABLE rezyserzy CASCADE;
DROP TABLE panstwa CASCADE;
DROP TABLE gatunki CASCADE;
DROP TABLE wypozyczalnie CASCADE;
DROP TABLE godziny_otwarcia CASCADE;
DROP TABLE adresy CASCADE;


DROP VIEW informacja CASCADE;
DROP VIEW wypozyczalnie_dane CASCADE;
DROP VIEW dane_rezyserzy CASCADE;

CREATE TABLE gatunki(
	id_gatunek INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nazwa VARCHAR(30) NOT NULL
);

CREATE TABLE panstwa(
	id_kraj_pochodzenia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kraj VARCHAR(30) NOT NULL
);

CREATE TABLE glowni_aktorzy(
	id_glowny_aktor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	imie_i_nazwisko VARCHAR(50) NOT NULL,
	id_kraj_pochodzenia INTEGER NOT NULL REFERENCES panstwa(id_kraj_pochodzenia)ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE rezyserzy(
	id_rezysera INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	imie_i_nazwisko VARCHAR(50) NOT NULL,
	id_kraj_pochodzenia INTEGER NOT NULL REFERENCES panstwa(id_kraj_pochodzenia)ON DELETE CASCADE ON UPDATE CASCADE	
);

CREATE TABLE filmy(
	id_filmu INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_gatunek INTEGER NOT NULL REFERENCES gatunki(id_gatunek)ON DELETE CASCADE ON UPDATE CASCADE,
	czas_trwania INTEGER NOT NULL,
	rok INTEGER NOT NULL CHECK (rok>1900),
	nazwa VARCHAR(50) NOT NULL,
	id_kraj_pochodzenia INTEGER NOT NULL REFERENCES panstwa(id_kraj_pochodzenia)ON DELETE CASCADE ON UPDATE CASCADE,
	id_rezysera INTEGER NOT NULL REFERENCES rezyserzy(id_rezysera),
	id_glowny_aktor INTEGER NOT NULL REFERENCES glowni_aktorzy(id_glowny_aktor)
	);


CREATE TABLE godziny_otwarcia(
	id_godziny_otwarcia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	otwarcie VARCHAR(10) NOT NULL,
	zamkniecie VARCHAR(10) NOT NULL
);

CREATE TABLE adresy(
	id_adres INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ulica VARCHAR(50) NOT NULL,
	nr_lokalu VARCHAR(10) NOT NULL,
	miasto VARCHAR(30) NOT NULL,
	kod_pocztowy VARCHAR(6) NOT NULL CHECK (kod_pocztowy ~ '^[0-9]{2}-[0-9]{3}$')
);

CREATE TABLE wypozyczalnie(
	id_wypozyczalni INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nazwa VARCHAR (40) NOT NULL UNIQUE,
	id_adres INTEGER NOT NULL REFERENCES adresy(id_adres)ON DELETE CASCADE ON UPDATE CASCADE,
	id_godziny_otwarcia INTEGER NOT NULL REFERENCES godziny_otwarcia(id_godziny_otwarcia)ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE baza(
	id_egzemplarza INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_wypozyczalni INTEGER NOT NULL REFERENCES wypozyczalnie(id_wypozyczalni)ON DELETE CASCADE ON UPDATE CASCADE,
	id_filmu INTEGER NOT NULL REFERENCES filmy(id_filmu)ON DELETE CASCADE ON UPDATE CASCADE,
	czy_dostepny BOOLEAN NOT NULL DEFAULT(true)
);

CREATE VIEW informacja AS( 
	SELECT b.id_egzemplarza, a1.tytul, a1.gatunek, a1.Dlugosc_filmu, a1.Rezyser, a1.Aktor_glowny,a1.Pochodzenie, w.nazwa AS Wypozyczalnia, b.czy_dostepny 
	FROM baza b JOIN wypozyczalnie w USING(id_wypozyczalni) JOIN 
		(SELECT f.id_glowny_aktor,g.nazwa AS Gatunek, f.id_filmu, f.nazwa AS tytul, f.czas_trwania AS Dlugosc_filmu, r.imie_i_nazwisko AS Rezyser, a2.Aktor_glowny, a2.Pochodzenie
		FROM filmy f JOIN gatunki g USING(id_gatunek) 
		JOIN rezyserzy r USING(id_rezysera)
		JOIN
		(SELECT a.imie_i_nazwisko AS Aktor_glowny, a.id_glowny_aktor, p.kraj AS Pochodzenie 
		FROM glowni_aktorzy a JOIN panstwa p USING(id_kraj_pochodzenia)) AS a2 USING(id_glowny_aktor)) AS a1
		USING(id_filmu));
		
CREATE VIEW wypozyczalnie_dane AS(
			SELECT w.nazwa, a.ulica, a.nr_lokalu, a.kod_pocztowy,g.otwarcie, g.zamkniecie 
			FROM wypozyczalnie w JOIN adresy a USING(id_adres)
			JOIN godziny_otwarcia g USING(id_godziny_otwarcia));
CREATE VIEW dane_rezyserzy AS(
	SELECT r.imie_i_nazwisko, p.kraj AS kraj_pochodzenia FROM rezyserzy r JOIN panstwa p USING(id_kraj_pochodzenia));

INSERT INTO gatunki(nazwa) VALUES
('Dramat'),
('Gangsterski'),
('Dramat Sadowy'),
('Fantasy'),
('Kryminal'),
('Psychologiczny'),
('Biograficzny'),
('Surrealistyczny'),
('Western'),
('Thriller'),
('Animacja'),
('Dramat historyczny'),
('Wojenny');

INSERT INTO panstwa(kraj) VALUES
	('USA'),
	('Francja'),
	('Niemcy'),
	('Wielka Brytania'),
	('Wlochy'),
	('Portoryko'),
	('Turcja'),
	('Nowa Zelandia'),
	('Syria'),
	('Izrael'),
	('Rosja'),
	('Szwecja'),
	('Czechy'),
	('Polska');
	
INSERT INTO glowni_aktorzy(imie_i_nazwisko, id_kraj_pochodzenia) VALUES
	('Tim Robbins', 1),
	('Francois Cluzet', 2),
	('Tom Hanks', 1),
	('Marlon Brando', 1),
	('Henry Fonda', 1),
	('Jack Nicholson', 1),
	('Al Pacino', 1),
	('Elijah Wood', 1),
	('Liam Neeson', 4),
	('John Travolta',1),
	('Roberto Benigni', 5),
	('Morgan Freeman',1),
	('Ray Liotta', 1),
	('Joaquin Phoenix', 6),
	('Aras Bulut İynemli', 7), 
	('Adrien Brody', 1),
	('Russel Crowe', 8),
	('Clint Eastwood', 1),
	('Zain Al Rafeea',9),
	('Viggo Mortensen', 1),
	('Edward Norton', 1),
	('Robert de Niro', 1),
	('Leonardo Di Caprio', 1),
	('Jaimie Foxx',1),
	('Anthony Hopkins', 4),
	('James Earl Jones',1),
	('Anthony Gonzales', 1),
	('Martin Sheen', 1),
	('Natalie Portman', 10),
	('Andrew Garfield', 1),
	('Miles Teller', 1),
	('Mel Gibson',1),
	('Asa Butterfield',4);

INSERT INTO rezyserzy(imie_i_nazwisko, id_kraj_pochodzenia) VALUES
	('Frank Darabont',2),
	('Olivier Nakache', 2),
	('Francis Ford Copolla',1),
	('Sidney Lumet', 1),
	('Robert Zemeckis', 1),
	('Milos Forman',13),
	('Peter Jackson', 8),
	('Steven Spielberg', 1),
	('Quentin Tarantino', 1),
	('Roberto Benigni', 5),
	('David Fincher', 1),
	('Martin Scorsese',1),
	('Todd Phillips', 1),
	('Roman Polanski',14),
	('Ron Howard', 1),
	('Christopher Nolan', 4),
	('Jonathan Demme', 1),
	('Rob Minkoff', 1),
	('Brian de Palma', 1),
	('Clint Eastwood', 1),
	('Lee Unkrich', 1),
	('Luc Besson', 2),
	('Tony Kaye', 4),
	('Peter Farelly', 1),
	('Ridley Scott', 4),
	('Mel Gibson',1),
	('Mark Herman', 4),
	('Damien Chazelle', 1);
	
INSERT INTO filmy(id_gatunek, czas_trwania, rok, nazwa, id_kraj_pochodzenia, id_rezysera, id_glowny_aktor) VALUES
	(1, 142, 2002, 'Skazani na Shawshank', 1, 1,1),
	(1, 112, 2011, 'Nietykalni', 2,2,2),
	(1, 188, 1999, 'Zielona mila', 1,1,3),
	(2, 175, 1972, 'Ojciec chrzestny', 1,3, 4),
	(3, 96, 1957, 'Dwunastu gniewnych ludzi', 1,4,5),
	(1, 144, 1994, 'Forrest Gump', 1,5,3),
	(1, 133, 1975, 'Lot nad kukulczym gniazadem', 1,6,6),
	(2, 200, 1974, 'Ojciec chrzestny 2', 1,3,7),
	(4, 201, 2003, 'Wladca Pierscieni: Powrot Krola', 1,7,8),
	(1, 205, 1993, 'Lista Schindlera', 1, 8,9),
	(2, 154, 1994, 'Pulp Fiction', 1, 9,10),
	(1, 114, 1997, 'Zycie jest piekne', 5, 10, 11),
	(5, 127, 1995, 'Siedem', 1, 11,12),
	(2,179, 2002, 'Wladca Pierscieni: Dwie Wieze', 1,7,8),
	(6, 139, 1999, 'Podziemny krag', 1, 11,21),
	(2, 143,1990, 'Chlopcy z ferajny', 1, 12, 13),
	(1, 122, 2019, 'Joker', 1, 13,14),
	(1, 150, 2002, 'Pianista', 14,14,16),
	(1, 135, 2001, 'Piekny umysl', 1, 15,17),
	(8, 148, 2010, 'Incepcja', 1, 16,23),
	(9, 165, 2012, 'Django', 1,9,24),
	(8, 118, 1991, 'Milczenie owiec', 1, 17, 25),
	(11,89, 1994, 'Krol Lew', 1, 18, 26),
	(2, 170, 1983, 'Czlowiek z blizna', 1, 19,7),
	(1, 116, 2008, 'Gran Torino', 1, 20,18),
	(11, 105, 2017, 'Coco', 1,21,27),
	(1,138, 2010, 'Wyspa tajemnic', 1, 12,23),
	(5, 110, 1994, 'Leon zawodowiec', 2,22,29),
	(1, 119, 1998, 'Więzień nienawisci', 1,23,21),
	(1, 130, 2018, 'Green book', 1, 24,20),
	(12, 155, 2000, 'Gladiator', 1, 25,17),
	(13, 170, 1998, 'Szeregowiec Ryan', 1, 8,3),
	(12, 177, 1995, 'Braveheart- waleczne serce', 1, 26, 32),
	(1, 93, 2008, 'Chlopiec w pasiastej pizamie', 1, 27, 33),
	(1, 105, 2014, 'Whiplash', 1, 28,31);
	
INSERT INTO godziny_otwarcia(otwarcie, zamkniecie) VALUES
	('8:00', '17:00'),
	('9:00', '18:00'),
	('8:00', '13:00'),
	('7:00', '11:00');
	
INSERT INTO adresy(ulica, nr_lokalu, miasto, kod_pocztowy) VALUES
	('malomiasteczkowa', '3', 'Wroclaw', '50-355'),
	('falowa', '15', 'Wroclaw', '40-431'),
	('inzynierska', '21', 'Wroclaw', '55-400'),
	('psia', '63', 'Siechnice', '43-514');
	
INSERT INTO wypozyczalnie (nazwa, id_adres, id_godziny_otwarcia) VALUES
	('Filmoteka', 1, 1),
	('Kinomaniacy', 2,2),
	('Baza', 3,3),
	('Magayn', 4,4);
	
	
INSERT INTO baza(id_wypozyczalni, id_filmu, czy_dostepny) VALUES
	(1,1,TRUE),
	(1,2,TRUE),
	(3,3,TRUE),
	(2,4, FALSE),
	(4,5,FALSE),
	(1,6,TRUE),
	(4,7,TRUE),
	(2,8,FALSE),
	(4,9,TRUE),
	(1,10,FALSE),
	(1,11,TRUE),
	(2,12,TRUE),
	(4,13,TRUE),
	(1,14,FALSE),
	(2,15,TRUE),
	(1,16,FALSE),
	(4,17,TRUE),
	(4,18,TRUE),
	(1,19,TRUE),
	(3,20,FALSE),
	(3,21,TRUE),
	(3,22,TRUE),
	(1,23,FALSE),
	(1,24,TRUE),
	(2,25,TRUE),
	(2,26,FALSE),
	(1,27,TRUE),
	(4,28,TRUE),
	(1,29,TRUE),
	(4,30,TRUE),
	(3,31,TRUE),
	(2,32,TRUE),
	(2,33,TRUE),
	(2,34,TRUE),
	(1,35,TRUE),
	(2,1,TRUE),
	(4,2,FALSE),
	(4,3,TRUE),
	(1,4,TRUE),
	(1,5,TRUE),
	(1,6,FALSE),
	(2,7,TRUE),
	(3,8,TRUE),
	(4,9,TRUE),
	(1,10,FALSE),
	(1,11,TRUE),
	(2,12,TRUE),
	(4,13,TRUE),
	(2,14,FALSE),
	(3,15,TRUE),
	(4,16,TRUE),
	(1,17,TRUE),
	(4,18,TRUE),
	(1,19,FALSE),
	(2,20,TRUE),
	(3,21,TRUE),
	(4,22,FALSE),
	(2,23,FALSE),
	(3,24,TRUE),
	(1,25,TRUE),
	(4,26,TRUE),
	(2,27,TRUE),
	(1,28,TRUE),
	(3,29,TRUE),
	(3,30,TRUE),
	(3,31,TRUE),
	(1,32,FALSE),
	(4,33,TRUE),
	(1,34,TRUE),
	(4,35,TRUE),
	(3,1,FALSE),
	(3,2,TRUE),
	(4,3,TRUE),
	(2,4,FALSE),
	(1,5,TRUE),
	(2,6,TRUE),
	(2,7,FALSE),
	(1,8,TRUE),
	(4,9,FALSE),
	(3,10,TRUE),
	(2,11,TRUE),
	(1,12,FALSE),
	(1,13,TRUE),
	(2,14,TRUE),
	(3,15,TRUE),
	(4,16,TRUE),
	(4,17,TRUE),
	(3,18,TRUE),
	(3,19,TRUE),
	(4,20,FALSE),
	(2,21,FALSE),
	(2,22,FALSE),
	(4,23,FALSE),
	(4,24,TRUE),
	(2,25,TRUE),
	(3,26,TRUE),
	(1,27,FALSE),
	(1,28,TRUE),
	(2,29,TRUE),
	(4,30,FALSE),
	(3,31,TRUE),
	(3,32,TRUE),
	(2,33,TRUE),
	(1,34,FALSE),
	(4,35,TRUE);
	
SELECT * FROM informacja;
SELECT * FROM wypozyczalnie_dane;
SELECT * FROM dane_rezyserzy;

		
